[project]
name = "using-cognite-python-sdk"
version = "0.1.0"
description = ""
authors = [
    { name = "Cognite", email = "academy@cognite.com" }
]
requires-python = ">=3.11,<4.0"
dependencies = [
    "cognite-sdk[pandas]>=8.0.0rc1,<9.0.0",
    "notebook>=7.5.3,<8.0.0",
]

[tool.uv]
package = false